config:
  Subscribers:
    # flag - operation PC
    - topic_name: 'write/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R10000'
    - topic_name: 'write/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R10001'
    - topic_name: 'write/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R10002'
    - topic_name: 'write/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R10003'
    # flag - machine
    - topic_name: 'write/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R10800'
    - topic_name: 'write/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R10801'
    - topic_name: 'write/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R10802'
    - topic_name: 'write/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R10803'
    - topic_name: 'write/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R10804'
    # setting
    - topic_name: 'write/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM150'

  Publishers:
    # flag - operation PC
    - topic_name: 'read/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R10000'
    - topic_name: 'read/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R10001'
    - topic_name: 'read/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R10002'
    - topic_name: 'read/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R10003'
    # flag - machine
    - topic_name: 'read/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R10800'
    - topic_name: 'read/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R10801'
    - topic_name: 'read/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R10802'
    - topic_name: 'read/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R10803'
    - topic_name: 'read/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R10804'
    # setting
    - topic_name: 'read/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM150'
