config:
  Subscribers:
    # flag - operation PC
    - topic_name: 'write/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R12000'
    - topic_name: 'write/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R12001'
    - topic_name: 'write/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R12002'
    - topic_name: 'write/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R12003'
    # flag - machine
    - topic_name: 'write/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R12800'
    - topic_name: 'write/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R12801'
    - topic_name: 'write/program_start'
      topic_type: 'Bool'
      plc_dev:    'R12802'
    - topic_name: 'write/program_end'
      topic_type: 'Bool'
      plc_dev:    'R12803'
    - topic_name: 'write/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R12804'
    - topic_name: 'write/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R12805'
    - topic_name: 'write/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R12806'
    #
    - topic_name: 'write/reset_press_force'
      topic_type: 'Bool'
      plc_dev:    'R12100'
    # setting
    - topic_name: 'write/press_force/setting'
      topic_type: 'Int16'
      plc_dev:    'DM610'  # read/write common
    - topic_name: 'write/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM612'  # read/write common
    - topic_name: 'write/sample_no/setting'
      topic_type: 'Int16'
      plc_dev:    'DM614'  # read/write common. 614 - 619

  Publishers:
    # flag - operation PC
    - topic_name: 'read/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R12000'
    - topic_name: 'read/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R12001'
    - topic_name: 'read/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R12002'
    - topic_name: 'read/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R12003'
    # flag - machine
    - topic_name: 'read/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R12800'
    - topic_name: 'read/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R12801'
    - topic_name: 'read/program_start'
      topic_type: 'Bool'
      plc_dev:    'R12802'
    - topic_name: 'read/program_end'
      topic_type: 'Bool'
      plc_dev:    'R12803'
    - topic_name: 'read/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R12804'
    - topic_name: 'read/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R12805'
    - topic_name: 'read/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R12806'
    # sensor
    - topic_name: 'read/temp_top'
      topic_type: 'Int16'
      plc_dev:    'DM600'
    - topic_name: 'read/temp_bottom'
      topic_type: 'Int16'
      plc_dev:    'DM602'
    - topic_name: 'read/press_force'
      topic_type: 'Int16'
      plc_dev:    'DM604'
    - topic_name: 'read/press_time'
      topic_type: 'Int32'
      plc_dev:    'DM606'
    - topic_name: 'read/press_pressure'
      topic_type: 'Int16'
      plc_dev:    'DM608'
    # setting
    - topic_name: 'read/press_force/setting'
      topic_type: 'Int16'
      plc_dev:    'DM610'  # read/write common
    - topic_name: 'read/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM612'  # read/write common
    - topic_name: 'read/sample_no/setting'
      topic_type: 'Int16'
      plc_dev:    'DM614'  # 614 - 619
