config:
  Subscribers:
    # flag - operation PC
    - topic_name: 'write/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R3000'
    - topic_name: 'write/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R3001'
    - topic_name: 'write/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R3002'
    - topic_name: 'write/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R3003'
    # flag - machine
    - topic_name: 'write/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R3800'
    - topic_name: 'write/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R3801'
    - topic_name: 'write/program_start'
      topic_type: 'Bool'
      plc_dev:    'R3802'
    - topic_name: 'write/program_end'
      topic_type: 'Bool'
      plc_dev:    'R3803'
    - topic_name: 'write/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R3804'
    - topic_name: 'write/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R3805'
    - topic_name: 'write/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R3806'
    #
    - topic_name: 'write/reset_press_force'
      topic_type: 'Bool'
      plc_dev:    'R3100'
    # setting
    - topic_name: 'write/seg0/temp_top/setting'
      topic_type: 'Int16'
      plc_dev:    'DM3000'
    - topic_name: 'write/seg0/temp_bottom/setting'
      topic_type: 'Int16'
      plc_dev:    'DM3004'
    - topic_name: 'write/seg0/press_force/setting'
      topic_type: 'Int16'
      plc_dev:    'DM3008'
    - topic_name: 'write/seg0/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM3012'

  Publishers:
    # flag - operation PC
    - topic_name: 'read/operation_start'
      topic_type: 'Bool'
      plc_dev:    'R3000'
    - topic_name: 'read/operation_reset'
      topic_type: 'Bool'
      plc_dev:    'R3001'
    - topic_name: 'read/carry_in_complete'
      topic_type: 'Bool'
      plc_dev:    'R3002'
    - topic_name: 'read/carry_out_complete'
      topic_type: 'Bool'
      plc_dev:    'R3003'
    # flag - machine
    - topic_name: 'read/start_waiting'
      topic_type: 'Bool'
      plc_dev:    'R3800'
    - topic_name: 'read/fullauto_running'
      topic_type: 'Bool'
      plc_dev:    'R3801'
    - topic_name: 'read/program_start'
      topic_type: 'Bool'
      plc_dev:    'R3802'
    - topic_name: 'read/program_end'
      topic_type: 'Bool'
      plc_dev:    'R3803'
    - topic_name: 'read/carry_in_possible'
      topic_type: 'Bool'
      plc_dev:    'R3804'
    - topic_name: 'read/carry_out_possible'
      topic_type: 'Bool'
      plc_dev:    'R3805'
    - topic_name: 'read/fullauto_end'
      topic_type: 'Bool'
      plc_dev:    'R3806'
    # sensor
    - topic_name: 'read/temp_top'
      topic_type: 'Int16'
      plc_dev:    'DM600'
    - topic_name: 'read/temp_bottom'
      topic_type: 'Int16'
      plc_dev:    'DM602'
    - topic_name: 'read/temp_plate'
      topic_type: 'Int16'
      plc_dev:    'DM604'
    - topic_name: 'read/press_force'
      topic_type: 'Int16'
      plc_dev:    'DM606'
    - topic_name: 'read/press_time'
      topic_type: 'Int32'
      plc_dev:    'DM608'
    - topic_name: 'read/press_pressure'
      topic_type: 'Int16'
      plc_dev:    'DM610'
    # setting
    - topic_name: 'read/temp_top/setting'
      topic_type: 'Int16'
      plc_dev:    'DM620'
    - topic_name: 'read/temp_bottom/setting'
      topic_type: 'Int16'
      plc_dev:    'DM622'
    - topic_name: 'read/press_force/setting'
      topic_type: 'Int16'
      plc_dev:    'DM624'
    - topic_name: 'read/press_time/setting'
      topic_type: 'Int32'
      plc_dev:    'DM626'
    - topic_name: 'read/sample_no/setting'
      topic_type: 'Int16'
      plc_dev:    'DM628'  # 628 - 633
    - topic_name: 'read/segment_no_in_progress/setting'
      topic_type: 'Int16'
      plc_dev:    'DM634'
