# device = device_type + device_num
heatpress:
  # for PC
  # R3000: 運転スタート
  # R3001: 運転リセット
  # R3002: 搬入完了
  # R3003: 搬出完了

  # for heatpress
  # R3800: スタート待機中
  # R3801: 自動運転中
  # R3802: プログラムスタート
  # R3803: プログラムエンド
  # R3804: サンプル搬入可
  # R3805: サンプル搬出可
  # R3806: 全自動運転終了

  # write device
  dev_operation_start    : "R3000"
  dev_operation_reset    : "R3001"
  dev_carry_in_complete  : "R3002"
  dev_carry_out_complete : "R3003"

  dev_start_waiting      : "R3800"
  dev_fullauto_running   : "R3801"
  dev_program_start      : "R3802"
  dev_program_end        : "R3803"
  dev_carry_in_possible  : "R3804"
  dev_carry_out_possible : "R3805"
  dev_fullauto_end       : "R3806"

  dev_reset_press_force  : "R3100"

  # read device
  dev_temp_top       : "DM600"
  dev_temp_bottom    : "DM602"
  dev_temp_plate     : "DM604"
  dev_press_force    : "DM606"
  dev_press_time     : "DM608"
  dev_press_pressure : "DM610"

  dev_setting_temp_top     : "DM620"
  dev_setting_temp_bottom  : "DM622"
  dev_setting_press_force  : "DM624"
  dev_setting_press_time   : "DM626"
  dev_setting_sample_no    : "DM628"  # 628 - 633


coldpress:
  # R12000: 運転スタート
  # R12001: 運転リセット
  # R12002: サンプル搬入完了
  # R12003: サンプル搬出完了
  #
  # for coldpress
  # R12800: スタート待機中
  # R12801: 自動運転中
  # R12802: プログラムスタート
  # R12803: プログラムエンド
  # R12804: サンプル搬入可
  # R12805: サンプル搬出可
  # R12806: 全自動運転終了

  # write
  dev_operation_start    : "R12000"
  dev_operation_reset    : "R12001"
  dev_carry_in_complete  : "R12002"
  dev_carry_out_complete : "R12003"

  dev_start_waiting      : "R12800"
  dev_fullauto_running   : "R12801"
  dev_carry_in_possible  : "R12804"
  dev_carry_out_possible : "R12805"
  dev_fullauto_end       : "R12806"

  dev_reset_press_force  : "R12100"

  # read
  dev_start_waiting      : "R12800"
  dev_fullauto_running   : "R12801"
  dev_program_start      : "R12802"
  dev_program_end        : "R12803"
  dev_carry_in_possible  : "R12804"
  dev_carry_out_possible : "R12805"
  dev_fullauto_end       : "R12806"

  dev_temp_top       : "DM600"
  dev_temp_bottom    : "DM602"
  dev_press_force    : "DM604"
  dev_press_time     : "DM606"
  dev_press_pressure : "DM608"

  dev_setting_press_force  : "DM610"
  dev_setting_press_time   : "DM612"
  dev_setting_sample_no    : "DM614" #614 - 619
