config:
  candidates:
    label: ['x1', 'x2', 'x3', 'y']
    param:
      # INT format is better for COMBO/PHYSBO
      - x1: [100, 200]  # [degC]
        x2: [10, 50]    # [N]
        x3: [0, 2, 5]   # [sec]
